import pandas as pd

df = pd.read_csv('data/oe2/bess/bess_ano_2024.csv')
print(f'Rows: {len(df)}')
print(f'\n📊 PEAK SHAVING METRICS v5.6.1:')
print(f'  Total Energy: {df["peak_shaving_kwh"].sum():>14,.0f} kWh/year')
print(f'  Active Hours: {(df["peak_shaving_kwh"] > 0).sum():>14} hours')
print(f'  Avg per Hour (active): {df[df["peak_shaving_kwh"] > 0]["peak_shaving_kwh"].mean():>10,.0f} kW')
print(f'\n⚡ ENERGY FLOWS (Annual):')
print(f'  BESS→EV:          {df["bess_to_ev_kwh"].sum():>12,.0f} kWh')
print(f'  BESS→MALL (Peak): {df["bess_to_mall_kwh"].sum():>12,.0f} kWh')
print(f'  PV→BESS Stored:   {df["pv_to_bess_kwh"].sum():>12,.0f} kWh')
print(f'  PV→EV Direct:     {df["pv_to_ev_kwh"].sum():>12,.0f} kWh')
print(f'  PV→MALL Direct:   {df["pv_to_mall_kwh"].sum():>12,.0f} kWh')
print(f'  Grid Export:      {df["grid_export_kwh"].sum():>12,.0f} kWh')
print(f'  Grid Import:      {df["grid_import_kwh"].sum():>12,.0f} kWh')
print(f'\n🔋 SOC Statistics (stored as raw basis points):')
print(f'  Min: {df["soc_percent"].min()/100:.1%}')
print(f'  Max: {df["soc_percent"].max()/100:.1%}')
print(f'  Mean: {df["soc_percent"].mean()/100:.1%}')
