import pandas as pd
base = pd.read_csv('analyses/oe3/co2_comparison_table.csv')
baseline = base.loc[base['escenario']=='Emisiones transporte base (combustión)', 'kgco2_anual'].item()
control = base.loc[base['escenario']=='Emisiones transporte electrificado + FV+BESS + control', 'kgco2_anual'].item()
no_agent = base.loc[base['escenario']=='Emisiones transporte electrificado + FV+BESS sin control', 'kgco2_anual'].item()
print('baseline (combustión) kgCO2/año:', baseline)
print('sin agente (PV+BESS) kgCO2/año:', no_agent)
print('control (A2C) kgCO2/año:', control)
print('reduction baseline -> sin agente:', baseline - no_agent)
print('reduction sin agente -> control:', no_agent - control)
print('total reduction baseline -> control:', baseline - control)
ctl = pd.read_csv('analyses/oe3/co2_control_vs_uncontrolled.csv')
print('\nDirecta (baseline_uncontrolled):', ctl.loc[ctl['metric']=='direct_avoided_kgco2_y','baseline_uncontrolled'].iat[0])
print('Indirecta (baseline_uncontrolled):', ctl.loc[ctl['metric']=='indirect_avoided_kgco2_y','baseline_uncontrolled'].iat[0])
print('Net avoided baseline_uncontrolled:', ctl.loc[ctl['metric']=='net_avoided_kgco2_y','baseline_uncontrolled'].iat[0])
print('Directa control_best:', ctl.loc[ctl['metric']=='direct_avoided_kgco2_y','controlled_best'].iat[0])
print('Indirecta control_best:', ctl.loc[ctl['metric']=='indirect_avoided_kgco2_y','controlled_best'].iat[0])
print('Net avoided control_best:', ctl.loc[ctl['metric']=='net_avoided_kgco2_y','controlled_best'].iat[0])
